platform: x64
clone_folder: c:\gopath\src\github.com\tzdybal\versiontest
os: Visual Studio 2015
environment:
  GOPATH: c:\gopath
build_script:
  - go env
  - go build -ldflags "-X main.Version=0.0.1"
  - versiontest
  - go clean -r -i
  - go get -ldflags "-X main.Version=0.0.1" github.com/tzdybal/versiontest
  - '%GOPATH%\bin\versiontest.exe'

